### ISSUE TITLE
Pagination Styling

### ISSUE THREAD

**Issue by Salman18** [aryaminus/RN-intro-screen#1]
# I want to move the active dot on left side and others on the right side.

What and all the changes I have to do to get this ?

**Comment by aryaminus** [comment]
Can you be a bit more specific? I am not getting your point here

**Comment by Salman18** [comment]
![screenshot from 2018-04-09 12-04-49](https://user-images.githubusercontent.com/21080254/38482779-483dd57c-3bee-11e8-8a30-0b5efc2b95b9.png)

As  you see above screenshot .

I want make active dots on the left side and remaining dots in right side. I want separate .
Pagination styling.

**Comment by aryaminus** [comment]
If you write under Swiper Stylesheet:
`
dot: {
    backgroundColor: "rgba(0,0,0,.25)",
    width: 30,
    height: 12,
    borderRadius: 6,
    marginLeft: 35,
    marginRight: 35,
    marginTop: 3,
    marginBottom: 3
},
`
Otherwise you would have to create different stylesheet for active and position

**Comment by Salman18** [comment]
Okay .

I tried but Unable to move it .
