### ISSUE TITLE
Header Issue

### ISSUE THREAD

**Issue by kalyanipullela** [aryaminus/RN-intro-screen#3]
Hiii @aryaminus 
I am using your Swiper code for my project but i am facing an issue that on the top of screen its getting white like a header
am attaching the screenshot of the issue .
can u pls check it once and help me with a solution.
![screenshot_1532101893](https://user-images.githubusercontent.com/38915385/43012152-3d5c5b90-8c63-11e8-8fa3-77a0ff97877e.png)

**Comment by aryaminus** [comment]
Configure the header styles in [Screen.js](https://github.com/aryaminus/RN-intro-screen/blob/master/app/components/Screen.js#L53) to match your Color code or else try hiding header with status bar
