### ISSUE TITLE
How can i delete the continue button?

### ISSUE THREAD

**Issue by Nisharunnisaa** [aryaminus/RN-intro-screen#4]
Hi,
I am using your code in my project it's working well,
 but  I want to remove the "continue" button I just want "start now" button 
when I am trying to remove the button I am getting an error.
can you please help me out how to do that?
Thanks in advance

**Comment by aryaminus** [comment]
Just change [this line](https://github.com/aryaminus/RN-intro-screen/blob/master/app/components/Swiper.js#L264) to:
```
<Button
            text="Start Now"
            onPress={() => this.props.navigation.navigate("Boiler")}
/>
```

Should work

**Comment by Nisharunnisaa** [comment]
Hi @aryaminus 
Thanks for ur response,
I want to completely remove the button from the first two slides and I want the start now button only on the third screen.
Hope you got me

**Comment by aryaminus** [comment]
Just put
```
console.log("Other page"); on the very same line
```
Else, remove the condition from : in line 262
